function actualDurationPrec = determineStimPresentationTime(...
    SimData, trialNum)
% How long was the stimulus presented for? This will depend of the block
% type. 

% First work out how long it takes the current frame to clear.
clearTime = (1/SimData.Fps) - mod(SimData.Raw.RtPrec(trialNum), ...
    1/SimData.Fps);
clearTime(mod(SimData.Raw.RtPrec(trialNum), 1/SimData.Fps) == 0) = 0;

if strcmp(SimData.SimSettings.BlockSettings( ...
        SimData.Raw.BlockType(trialNum)).Type, 'free')
    
    actualDurationPrec = ...
        SimData.Raw.RtPrec(trialNum) + ...
        clearTime + ...
        SimData.SimSettings.BlockSettings( ...
        SimData.Raw.BlockType(trialNum)).StimAfterResp;
    
elseif strcmp(SimData.SimSettings.BlockSettings( ...
        SimData.Raw.BlockType(trialNum)).Type, 'forced')
    
    actualDurationPrec = min( ...
        [(SimData.Raw.RtPrec(trialNum) + clearTime), ...
        SimData.Raw.PlannedDuration(trialNum)]);
    
    if SimData.SimSettings.BlockSettings( ...
            SimData.Raw.BlockType(trialNum)).StimAfterResp ~= 0
        
        error(['After response stimulus does not make sense in a forced ' ...
            'response block.'])
    end
end